documentation 📚:
  - changed-files:
      - any-glob-to-any-file: ["docs/**", "*.md"]

DevOps 💻:
  - changed-files:
      - any-glob-to-any-file:
          [".github/**", "distribute.py", "rimdex.nuitka-package.config.yml"]

macOS 🍏:
  - changed-files:
      - any-glob-to-any-file: ["**/*.dylib"]

Linux🐧:
  - changed-files:
      - any-glob-to-any-file: ["**/*.so"]

Windows 🪟:
  - changed-files:
      - any-glob-to-any-file: ["**/*.dll"]

dependencies:
  - changed-files:
      - any-glob-to-any-file: ["requirements*.txt"]
