from __future__ import annotations

import fnmatch
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Always excluded in addition to `.gitignore` entries: VCS internals and the
# standard generated tool caches are not project structure, and `submodules` is
# a third-party submodule (matches the ignore list in `scripts/stats.py`).
ALWAYS_IGNORE = {
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".pytest_cache",
    "submodules",
}


def parse_gitignore(root: Path) -> list[tuple[str, bool, bool, bool]]:
    """Return (pattern, dir_only, anchored, negated) tuples from `.gitignore`."""
    path = root / ".gitignore"
    out: list[tuple[str, bool, bool, bool]] = []
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        negated = line.startswith("!")
        if negated:
            line = line[1:]
        dir_only = line.endswith("/")
        pat = line[:-1] if dir_only else line
        anchored = pat.startswith("/")
        if anchored:
            pat = pat[1:]
        out.append((pat, dir_only, anchored, negated))
    return out


def _excluded(
    rel: str, is_dir: bool, patterns: list[tuple[str, bool, bool, bool]]
) -> bool:
    parts = rel.split("/")
    name = parts[-1]
    excluded = False
    for pat, dir_only, anchored, negated in patterns:
        if anchored:
            candidates = [rel]
        else:
            candidates = (
                [rel, name]
                + ["/".join(parts[: i + 1]) for i in range(len(parts))]
                + ["/".join(parts[i:]) for i in range(len(parts))]
                + parts
            )
        for cand in candidates:
            if dir_only:
                if fnmatch.fnmatch(cand, pat) and (
                    rel == cand or rel.startswith(cand + "/") or cand in parts
                ):
                    excluded = not negated
                    break
                if cand.startswith(pat + "/"):
                    excluded = not negated
                    break
            else:
                if fnmatch.fnmatch(cand, pat) or cand.startswith(pat + "/"):
                    excluded = not negated
                    break
    return excluded


class _Node:
    __slots__ = ("children", "is_dir")

    def __init__(self, is_dir: bool) -> None:
        self.is_dir = is_dir
        self.children: dict[str, _Node] = {}


def _build_tree(dirs: set[str], files: list[str]) -> _Node:
    root = _Node(True)
    for rel in dirs:
        node = root
        for part in rel.split("/"):
            node = node.children.setdefault(part, _Node(True))
    for rel in files:
        parts = rel.split("/")
        node = root
        for part in parts[:-1]:
            node = node.children.setdefault(part, _Node(True))
        node.children[parts[-1]] = _Node(False)
    return root


def _render_children(children: dict[str, _Node], prefix: str, lines: list[str]) -> None:
    items = sorted(children.items(), key=lambda kv: (not kv[1].is_dir, kv[0].lower()))
    n = len(items)
    for i, (name, node) in enumerate(items):
        last = i == n - 1
        connector = "└── " if last else "├── "
        label = name + ("/" if node.is_dir else "")
        lines.append(prefix + connector + label)
        if node.is_dir:
            child_prefix = prefix + ("    " if last else "│   ")
            _render_children(node.children, child_prefix, lines)


def _render(root: _Node, root_name: str) -> list[str]:
    lines = [root_name + "/"]
    _render_children(root.children, "", lines)
    return lines


def main() -> int:
    patterns = parse_gitignore(ROOT)
    included_dirs: set[str] = set()
    included_files: list[str] = []

    stack: list[Path] = [ROOT]
    while stack:
        d = stack.pop()
        try:
            entries = sorted(d.iterdir())
        except (OSError, PermissionError):
            continue
        for e in entries:
            rel = e.relative_to(ROOT).as_posix()
            is_dir = e.is_dir()
            if e.name in ALWAYS_IGNORE or _excluded(rel, is_dir, patterns):
                continue
            if is_dir:
                included_dirs.add(rel)
                stack.append(e)
            else:
                included_files.append(rel)

    tree = _build_tree(included_dirs, included_files)
    tree_lines = _render(tree, ROOT.name)

    ignored = ", ".join(f"`{p}{'/' if d else ''}`" for p, d, _, n in patterns if not n)
    header = [
        "# Project Structure Map",
        "",
        (
            f"Generated by `scripts/mapping.py`. Excludes paths in `.gitignore`"
            f" ({ignored or 'none'}), plus `.git`, the generated tool caches"
            f" (`.mypy_cache/`, `.ruff_cache/`, `.pytest_cache/`) and the"
            f" `submodules/` directory. `.gitignore` `!` re-inclusions are honored."
        ),
        "",
    ]
    out_path = ROOT / "mapping.md"
    out_path.write_text("\n".join(header + tree_lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(included_files)} files, {len(included_dirs)} dirs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
